# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14799ed11faca5bc6d56099c71fb46679cb1a688c3cc9166ab0465f9940d276cfaec80745a6d9194d583446d9288932210ca47529040227b77440259b1033771

test:
  secret_key_base: bb5c9b3106ef40d17f7344e1560d5a6896d66731c3645fe248aa283c6fc66148f27103a95142cab5a2eccb5c3ed5529c72b881bee7fa935a9659b7a4b67f30ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
